[build]
  base    = "website"
  publish = "build"
  command = "npm run netlify-build"
  ignore = "git diff --quiet HEAD^ HEAD docs website"

[build.environment]
NODE_VERSION = "10"


[[redirects]]
  from = "*"
  to = "https://redux-toolkit.js.org/rtk-query/overview"
  status = 301
  force = true
