name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['12.x']
        os: [ubuntu-latest] #, windows-latest, macOS-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile  --ignore-scripts

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Pack (including Prepare)
        run: npm pack

      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: rtk-incubator-rtk-query*.tgz

  test:
    name: Test Types with TypeScript ${{ matrix.ts }}

    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ['12.x']
        ts: ['3.8', '3.9', '4.0', '4.1', '4.2', 'next']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile  --ignore-scripts

      - name: Install TypeScript ${{ matrix.ts }}
        run: npm install typescript@${{ matrix.ts }} --ignore-scripts

      - uses: actions/download-artifact@v2
        with:
          name: package

      - name: Unpack build artifact to dist
        run: tar -xzvf rtk-incubator-rtk-query-*.tgz --strip-components=1 package/dist

      - name: Remap @redux/toolkit from src to dist
        run: |
          sed -i -re 's|(@rtk-incubator/rtk-query.*)\./src|\1./|' ./test/tsconfig.json

      - name: "@ts-ignore stuff that didn't exist pre-4.1 in the tests"
        if: ${{ matrix.ts < 3.9 }}
        run: |
          sed -i 's/@ts-expect-error/@ts-ignore/' test/*.ts*

      - name: "@ts-ignore stuff that didn't exist pre-4.1 in the tests"
        if: ${{ matrix.ts < 4.1 }}
        run: |
          sed -i 's/@pre41-ts-ignore/@ts-ignore/' test/*.ts*

      - name: Test types
        run: |
          ./node_modules/.bin/tsc --version
          ./node_modules/.bin/tsc --project test/tsconfig.json --showConfig
          ./node_modules/.bin/tsc --project test/tsconfig.json
